DROP USER IF EXISTS 'ace-user'@'localhost';
FLUSH PRIVILEGES;
CREATE USER 'ace-user'@'localhost' IDENTIFIED BY 'ACE_DB_USER_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE ON `ace`.* TO 'ace-user'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON `ace-workload`.* TO 'ace-user'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON `amc`.* TO 'ace-user'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON `brocess`.* TO 'ace-user'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON `email-archive`.* TO 'ace-user'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON `hal9000`.* TO 'ace-user'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON `cloudphish`.* TO 'ace-user'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON `vt-hash-cache`.* TO 'ace-user'@'localhost';
FLUSH PRIVILEGES;
