#!/usr/bin/env bash
#

# if this file is a symlink then we assume we've already configured this for ACE
if [ -L /etc/memcached.conf ]
then
    exit 0
fi

if [ -e /etc/memcached.conf ]
then
    mv /etc/memcached.conf /etc/memcached.conf.bak
fi

ln -s $SAQ_HOME/etc/memcached.conf.example /etc/memcached.conf
systemctl restart memcached.service
exit 0
